services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-tracker-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://expenseUser:Kunjeda007@expense-tracker-cluster.mskmm0i.mongodb.net/expense-tracker?retryWrites=true&w=majority&appName=expense-tracker-cluster
      - JWT_SECRET=expense_tracker_super_secret_jwt_key_2025
      - PORT=8000
      - NODE_ENV=production
      - CLIENT_URL=http://localhost:3000
    networks:
      - expense-tracker-network

  frontend:
    build:
      context: ./frontend/expense-tracker
      dockerfile: Dockerfile
    container_name: expense-tracker-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - expense-tracker-network

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: expense-tracker-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - expense-tracker-network

  grafana:
    image: grafana/grafana:10.1.0
    container_name: expense-tracker-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - expense-tracker-network
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: expense-tracker-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - expense-tracker-network

networks:
  expense-tracker-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

